# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9845949a39884a63f0a412ac87f476d3af82955872fedd751d63ee2176d40212ae02a7c8eeb709e351408fd6febad6bee2bd0dac19d1b8af57a6b6de61e3996f

test:
  secret_key_base: 012d414e0bb48fc57969251252ae9fd20d1fa1ccb59d0b8749f9fef513f9a760be2ea0c850f67764af0b304d41885aa46563c193debbdbb32d320a025183b0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
